<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterVendorSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('master_vendors')->insert([
            [
                'Nama' => 'PT Medika Utama Sejahtera',
                'Alamat' => 'Jl. Jend. Sudirman No.10, Jakarta',
                'NoHp' => '08123456001',
                'Email' => 'sales@medikautama.co.id',
                'NamaPic' => 'Andi Pratama',
                'NoHpPic' => '08129876001',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Alkes Nusantara',
                'Alamat' => 'Jl. Raya Bogor KM 25, Depok',
                'NoHp' => '08123456002',
                'Email' => 'info@alkesnusantara.id',
                'NamaPic' => 'Budi Santoso',
                'NoHpPic' => '08129876002',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Sehat Medika Abadi',
                'Alamat' => 'Jl. Ahmad Yani No.55, Bandung',
                'NoHp' => '08123456003',
                'Email' => 'marketing@sehatmedika.co.id',
                'NamaPic' => 'Citra Lestari',
                'NoHpPic' => '08129876003',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'CV Global Sarana Medis',
                'Alamat' => 'Jl. Gatot Subroto No.88, Medan',
                'NoHp' => '08123456004',
                'Email' => 'globalsarana@gmail.com',
                'NamaPic' => 'Dewi Anggraini',
                'NoHpPic' => '08129876004',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Sumber Medika Jaya',
                'Alamat' => 'Jl. Veteran No.12, Pekanbaru',
                'NoHp' => '08123456005',
                'Email' => 'admin@sumbermedika.co.id',
                'NamaPic' => 'Eko Saputra',
                'NoHpPic' => '08129876005',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ---------- 6 - 20 ----------
            [
                'Nama' => 'PT Anugrah Alat Medis',
                'Alamat' => 'Jl. Soekarno Hatta No.21, Palembang',
                'NoHp' => '08123456006',
                'Email' => 'contact@anugrahalatmedis.co.id',
                'NamaPic' => 'Fajar Hidayat',
                'NoHpPic' => '08129876006',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Cipta Medika Persada',
                'Alamat' => 'Jl. Asia Afrika No.9, Bandung',
                'NoHp' => '08123456007',
                'Email' => 'info@ciptamedika.co.id',
                'NamaPic' => 'Gilang Ramadhan',
                'NoHpPic' => '08129876007',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Mitra Sehat Abadi',
                'Alamat' => 'Jl. Ahmad Dahlan No.18, Yogyakarta',
                'NoHp' => '08123456008',
                'Email' => 'sales@mitrasehatabadi.id',
                'NamaPic' => 'Hendra Wijaya',
                'NoHpPic' => '08129876008',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Sentosa Meditech',
                'Alamat' => 'Jl. Pemuda No.77, Semarang',
                'NoHp' => '08123456009',
                'Email' => 'support@sentosameditech.co.id',
                'NamaPic' => 'Indra Kurniawan',
                'NoHpPic' => '08129876009',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Prima Sarana Umum',
                'Alamat' => 'Jl. Diponegoro No.66, Surabaya',
                'NoHp' => '08123456010',
                'Email' => 'primasarana@gmail.com',
                'NamaPic' => 'Joko Santoso',
                'NoHpPic' => '08129876010',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Karya Medis Indonesia',
                'Alamat' => 'Jl. Gatot Subroto No.5, Jakarta',
                'NoHp' => '08123456011',
                'Email' => 'info@karyamedis.id',
                'NamaPic' => 'Kevin Adrian',
                'NoHpPic' => '08129876011',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Bina Alkes Mandiri',
                'Alamat' => 'Jl. Teuku Umar No.19, Denpasar',
                'NoHp' => '08123456012',
                'Email' => 'admin@binaalkes.co.id',
                'NamaPic' => 'Lukman Hakim',
                'NoHpPic' => '08129876012',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Sejahtera Sarana Medis',
                'Alamat' => 'Jl. A. Yani No.45, Balikpapan',
                'NoHp' => '08123456013',
                'Email' => 'sales@sejahterasaranamedis.id',
                'NamaPic' => 'M. Rizky',
                'NoHpPic' => '08129876013',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Global Medika Solusi',
                'Alamat' => 'Jl. Slamet Riyadi No.30, Solo',
                'NoHp' => '08123456014',
                'Email' => 'contact@globalmedika.id',
                'NamaPic' => 'Nanda Prakoso',
                'NoHpPic' => '08129876014',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Andalan Medis Utama',
                'Alamat' => 'Jl. Margonda Raya No.100, Depok',
                'NoHp' => '08123456015',
                'Email' => 'andalanmedis@gmail.com',
                'NamaPic' => 'Oscar Firmansyah',
                'NoHpPic' => '08129876015',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Nusantara Alat Kesehatan',
                'Alamat' => 'Jl. Sudirman No.90, Makassar',
                'NoHp' => '08123456016',
                'Email' => 'nusantaraalkes@gmail.com',
                'NamaPic' => 'Putra Mahendra',
                'NoHpPic' => '08129876016',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Cemerlang Medika',
                'Alamat' => 'Jl. Pahlawan No.14, Samarinda',
                'NoHp' => '08123456017',
                'Email' => 'info@cemerlangmedika.id',
                'NamaPic' => 'Randi Kurnia',
                'NoHpPic' => '08129876017',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Meditech Solusindo',
                'Alamat' => 'Jl. Dr. Sutomo No.22, Malang',
                'NoHp' => '08123456018',
                'Email' => 'meditech@gmail.com',
                'NamaPic' => 'Satria Wibowo',
                'NoHpPic' => '08129876018',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Amanah Sarana Medis',
                'Alamat' => 'Jl. MT Haryono No.50, Banjarmasin',
                'NoHp' => '08123456019',
                'Email' => 'amanahmedis@gmail.com',
                'NamaPic' => 'Taufik Hidayah',
                'NoHpPic' => '08129876019',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Nama' => 'PT Prima Medika Global',
                'Alamat' => 'Jl. Merdeka No.8, Padang',
                'NoHp' => '08123456020',
                'Email' => 'primamedikaglobal@gmail.com',
                'NamaPic' => 'Yusuf Akbar',
                'NoHpPic' => '08129876020',
                'Status' => 'Y',
                'UserCreate' => 'admin',
                'UserUpdate' => null,
                'UserDelete' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
